"""Add date and location to Event table

Revision ID: 1d48a50ff75f
Revises: c33de9fc7742
Create Date: 2024-01-17 20:47:48.696878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d48a50ff75f'
down_revision = 'c33de9fc7742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
